#include "KhonParts.h"

#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "SornTypes.h"

namespace
{
	// Materials generated by Content/Python/setup_project.py; engine fallback otherwise.
	const TCHAR* KhonMaterialPath = TEXT("/Game/Materials/M_Khon.M_Khon");
	const TCHAR* KhonTranslucentPath = TEXT("/Game/Materials/M_KhonTranslucent.M_KhonTranslucent");
	const TCHAR* FallbackMaterialPath = TEXT("/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial");

	const TCHAR* MeshPath(EKhonShape Shape)
	{
		switch (Shape)
		{
		case EKhonShape::Sphere: return TEXT("/Engine/BasicShapes/Sphere.Sphere");
		case EKhonShape::Cylinder: return TEXT("/Engine/BasicShapes/Cylinder.Cylinder");
		case EKhonShape::Cone: return TEXT("/Engine/BasicShapes/Cone.Cone");
		default: return TEXT("/Engine/BasicShapes/Cube.Cube");
		}
	}
}

UStaticMesh* UKhonMaterialSubsystem::Mesh(EKhonShape Shape)
{
	const uint8 Key = static_cast<uint8>(Shape);
	if (TObjectPtr<UStaticMesh>* Found = Meshes.Find(Key))
	{
		return *Found;
	}
	UStaticMesh* Loaded = LoadObject<UStaticMesh>(nullptr, MeshPath(Shape));
	Meshes.Add(Key, Loaded);
	return Loaded;
}

UMaterialInterface* UKhonMaterialSubsystem::BaseMaterial(bool bTranslucent)
{
	if (!Base)
	{
		Base = LoadObject<UMaterialInterface>(nullptr, KhonMaterialPath, nullptr, LOAD_NoWarn | LOAD_Quiet);
		BaseTranslucent = LoadObject<UMaterialInterface>(nullptr, KhonTranslucentPath, nullptr, LOAD_NoWarn | LOAD_Quiet);
		if (!Base)
		{
			UE_LOG(LogTemp, Warning, TEXT("M_Khon not found; run Content/Python/setup_project.py. Using engine fallback."));
			Base = LoadObject<UMaterialInterface>(nullptr, FallbackMaterialPath);
			bUsingFallback = true;
		}
		if (!BaseTranslucent)
		{
			BaseTranslucent = Base;
		}
	}
	return bTranslucent ? BaseTranslucent.Get() : Base.Get();
}

void UKhonMaterialSubsystem::SetMatColor(UMaterialInstanceDynamic* Mat, const FLinearColor& Color, float Opacity)
{
	if (!Mat)
	{
		return;
	}
	Mat->SetVectorParameterValue(TEXT("BaseColor"), Color);
	Mat->SetVectorParameterValue(TEXT("Color"), Color);
	Mat->SetScalarParameterValue(TEXT("Opacity"), Opacity);
}

UMaterialInterface* UKhonMaterialSubsystem::Mat(const FLinearColor& Color, float Metallic, float Roughness, float Emissive)
{
	const FString Key = FString::Printf(TEXT("%s|%.2f|%.2f|%.2f"), *Color.ToString(), Metallic, Roughness, Emissive);
	if (TObjectPtr<UMaterialInstanceDynamic>* Found = Cache.Find(Key))
	{
		return *Found;
	}
	UMaterialInstanceDynamic* M = UMaterialInstanceDynamic::Create(BaseMaterial(false), this);
	M->SetVectorParameterValue(TEXT("BaseColor"), Color);
	M->SetVectorParameterValue(TEXT("Color"), Color);
	M->SetScalarParameterValue(TEXT("Metallic"), Metallic);
	M->SetScalarParameterValue(TEXT("Roughness"), Roughness);
	M->SetScalarParameterValue(TEXT("Emissive"), Emissive);
	Cache.Add(Key, M);
	return M;
}

UMaterialInstanceDynamic* UKhonMaterialSubsystem::UniqueMat(UObject* Outer, const FLinearColor& Color, float Emissive, bool bTranslucent)
{
	UMaterialInstanceDynamic* M = UMaterialInstanceDynamic::Create(BaseMaterial(bTranslucent), Outer);
	M->SetScalarParameterValue(TEXT("Emissive"), Emissive);
	M->SetScalarParameterValue(TEXT("Roughness"), 0.6f);
	SetMatColor(M, Color, 1.f);
	return M;
}

namespace KhonParts
{
	UKhonMaterialSubsystem* Lib(const UObject* WorldContext)
	{
		const UWorld* World = WorldContext ? WorldContext->GetWorld() : nullptr;
		return World ? World->GetSubsystem<UKhonMaterialSubsystem>() : nullptr;
	}

	UMaterialInterface* Gold(const UObject* WorldContext)
	{
		return Lib(WorldContext)->Mat(Sorn::Col::Gold, 0.85f, 0.32f);
	}

	USceneComponent* Pivot(AActor* Owner, USceneComponent* Parent, const FVector& PosM, FName Name)
	{
		USceneComponent* C = NewObject<USceneComponent>(Owner, Name);
		C->SetupAttachment(Parent);
		C->SetRelativeLocation(Sorn::G(PosM.X, PosM.Y, PosM.Z));
		C->RegisterComponent();
		return C;
	}

	UStaticMeshComponent* Part(AActor* Owner, USceneComponent* Parent, EKhonShape Shape,
		UMaterialInterface* Material, const FVector& PosM, const FVector& Size, const FVector& RotDeg)
	{
		UStaticMeshComponent* C = NewObject<UStaticMeshComponent>(Owner);
		C->SetStaticMesh(Lib(Owner)->Mesh(Shape));
		C->SetMaterial(0, Material);
		C->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		C->SetGenerateOverlapEvents(false);
		C->SetCanEverAffectNavigation(false);
		C->SetupAttachment(Parent);
		C->SetRelativeLocation(Sorn::G(PosM.X, PosM.Y, PosM.Z));
		C->SetRelativeRotation(Sorn::RD(RotDeg.X, RotDeg.Y, RotDeg.Z));
		// Size is (right, up, back) in metres -> scale (X fwd, Y right, Z up); meshes are 1 m.
		C->SetRelativeScale3D(FVector(Size.Z, Size.X, Size.Y));
		C->RegisterComponent();
		return C;
	}
}
